### ISSUE TITLE
Addon crashes

### ISSUE THREAD

**Issue by sitolam** [jerryzhou196/seepreviousratings#19]
First the add-on works perfectly but after a while it just crashes with this error:
```
Anki 24.11 (87ccd24e)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.22631

Traceback (most recent call last):
  File "aqt.webview", line 665, in handler
  File "aqt.reviewer", line 789, in _onTypedAnswer
  File "aqt.reviewer", line 483, in _showAnswer
  File "_aqt.hooks", line 4229, in __call__
  File "C:\Users\Otis\AppData\Roaming\Anki2\addons21\1906641654\__init__.py", line 120, in init
    reviewType = types[rawRevType]
KeyError: 5

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Button Colours Good Again ['2494384865', 2022-09-27T12:18, 'None', '']
Copy notes ['1566928056', 2021-12-24T20:56, 'None', '']
Deck name in title 21 ['699175524', 2019-06-01T03:05, 'None', '']
Progress bar - Visualize reviewed cards and remaining Fixed by Shige ['1708250053', 2024-11-10T21:00, 'None', mod]
Review Heatmap ['1771074083', 2022-06-30T03:43, 'None', '']
See Previous Card Ratings in Reviewer ['1906641654', 2021-08-19T23:32, 'None', '']

===IDs of active AnkiWeb add-ons===
1566928056 1708250053 1771074083 1906641654 2494384865 699175524

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Image Occlusion Enhanced ['1374772155', 2022-04-09T09:15, 'None', '']
```

**Comment by tufnad** [comment]
yeah, its happening to me as well after the last update

**Comment by sitolam** [comment]
> yeah, its happening to me as well after the last update

I tested it in the previous version but it's also an issue there.

**Comment by jerryzhou196** [comment]
Looking into it. Thanks for the report!

**Comment by jerryzhou196** [comment]
Okay the addon has been updated to support the new type. Bug should be resolved.
